name: prometeo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - optuna
  - shap
  - matplotlib
  - seaborn
  - joblib
  - pip
  - pip:
    - PySide6
